### PR TITLE
BrowseSourceScreen: Adjust browse mode chips placement

### LINKED ISSUE #8056: BrowseSourceScreen: FilterChip's left margin is gone in list view
### Steps to reproduce

Switch to list view in BrowseSourceScreen.

### Expected behavior

FilterChip should have the correct margin.

### Crash logs

_No response_

### Tachiyomi version

r4929

### Android version

Android 12

### Device

Not related

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ivaniskandar**
The chips row is now scrollable too and filter fab is removed

Fixes #8056

image

### CODE REVIEW

File: app/src/main/java/eu/kanade/presentation/browse/BrowseSourceScreen.kt [hunk 1]
```diff
@@ -76,8 +82,8 @@ fun BrowseSourceScreen(
     }
 
     Scaffold(
-        topBar = { scrollBehavior ->
```
Comment (arkon) [inline app/src/main/java/eu/kanade/presentation/browse/BrowseSourceScreen.kt:79]: No more lift state elevation?

Comment (ivaniskandar) [reply app/src/main/java/eu/kanade/presentation/browse/BrowseSourceScreen.kt:79]: No the app bar now behaves like tabbed app bar. A divider below and no elevation
