### PR TITLE
Check if wifi is connected rather than enabled while downloading.

### LINKED ISSUE #6008: Chapter auto-downloads even when "wifi only" is enabled
### Steps to reproduce

1. tachiyomi setting was that chapters would only download when connected to Wifi
2. Had wifi functionality of phone enabled.
3. Did not connect to wifi
4. Had mobile data on
5. Updated chapters
6. Chapters updated and auto-downloaded

### Expected behavior

In this scenario, chapters should update but not download.

### Actual behavior

Chapters still download

### Crash logs

_No response_

### Tachiyomi version

Stable 0.12.2

### Android version

Android 11

### Device

Samsung S10+

### Other details

When I turn off Wifi, it does as expected. It no longer auto-downloads from mobile data.

Was referred by curche#0545 to post an issue.

Issue thread from discord starts here: https://discord.com/channels/349436576037732353/349436576037732355/893727232319717396

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FourTOne5**
Fixes #6008

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt [hunk 1]
```diff
@@ -379,6 +380,24 @@ fun Context.isOnline(): Boolean {
...
+/**
+ * Returns true if device is connected to wifi.
+ */
+fun Context.isConnectedToWifi(): Boolean {
+    if (!wifiManager.isWifiEnabled) return false
+
+    val wifiInfo: WifiInfo = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+        val activeNetwork = connectivityManager.activeNetwork ?: return false
+        val networkCapabilities = connectivityManager.getNetworkCapabilities(activeNetwork) ?: return false
+        networkCapabilities.transportInfo as WifiInfo
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt:392]: This _should_ work for Q and up, right?

Comment (FourTOne5) [reply app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt:392]: Yes.. Should I change it to Q?

Comment (arkon) [reply app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt:392]: Might as well, I'd say.
