### PR TITLE
Fix Crash while trying to search in Settings

### LINKED ISSUE #6395: app crashes when trying to search in settings
### Steps to reproduce

1. go to more>settings
2. click on the search icon

### Expected behavior

shud be able to search

### Actual behavior

app crashes

### Crash logs

--------- beginning of system
--------- beginning of main
12-27 16:04:00.879 19827 19827 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
12-27 16:04:00.879 19827 19827 E ACRA    : java.lang.NullPointerException
12-27 16:04:00.879 19827 19827 E ACRA    : 	at eu.kanade.tachiyomi.ui.setting.SettingsLibraryController.access$setupPreferenceScreen$lambda-35$lambda-34$lambda-31$updateSummary-30(SettingsLibraryController.kt:2)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at eu.kanade.tachiyomi.ui.setting.SettingsLibraryController$setupPreferenceScreen$1$3$4$2.invokeSuspend(SettingsLibraryController.kt:1)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at eu.kanade.tachiyomi.ui.setting.SettingsLibraryController$setupPreferenceScreen$1$3$4$2.invoke(Unknown Source:8)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at eu.kanade.tachiyomi.ui.setting.SettingsLibraryController$setupPreferenceScreen$1$3$4$2.invoke(Unknown Source:4)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:5)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:11)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at android.os.Looper.loop(Looper.java:236)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8019)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
12-27 16:04:00.879 19827 19827 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
12-27 16:04:01.044 20533 20533 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
12-27 16:04:04.245 20615 20615 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
12-27 16:04:04.777 20615 20662 E SQLiteLog: (284) automatic index on C(manga_id)
12-27 16:04:04.778 20615 20662 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.12.3-4045 (standard, 42accebec, 72, 2021-12-25T21:07Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.201022.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sunny
Device model: M2101K7AG
Device product name: sunny_global

### Tachiyomi version

r4045

### Android version

Android 11

### Device

Redmi Note 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FourTOne5**
Fixes #6395

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt [hunk 1]
```diff
@@ -230,8 +230,8 @@ class SettingsLibraryController : SettingsController() {
                 }
 
                 fun updateSummary() {
-                    val dbCategories = db.getCategories().executeAsBlocking()
-                    val allCategories = listOf(Category.createDefault(activity!!)) + dbCategories
+                    // +1 For default category
+                    val allCategoriesCount = db.getCategories().executeAsBlocking().size + 1
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt:234]: This probably isn't even needed at all, they're already declared at a higher scope.
