### PR TITLE
Fix checkboxes not working after scrolling in filter sheet

### LINKED ISSUE #9922: Tap not working in filter tab after scroll.
### Steps to reproduce

1. Open source with filters.
2. Open filter tab.
3. Scroll filter tab.
4. Try to tap on filter entries.

### Expected behavior

You should be able to switch filters.

### Actual behavior

You can't switch filters.

### Crash logs

_No response_

### Tachiyomi version

0.14.6-6049 (standard, 36f1e0e47, 105, 2023-09-09T21:09Z)

### Android version

Android 13

### Device

realme 10 Pro 5G

### Other details

You can use second finger to switch filters after scroll.
Video proof of the bug:

https://github.com/tachiyomiorg/tachiyomi/assets/54038231/f7750709-a1a3-4b4e-a3a6-22e1aebfe8f7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by prasidhgopalanchan**
## Fixed an issue where CheckBox was not being checked after scrolling in the Filter tab

Fixes #9922 

https://github.com/tachiyomiorg/tachiyomi/assets/92362239/98005543-471e-4532-bb52-6b75b135c3d5

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceFilterDialog.kt [hunk 1]
```diff
@@ -41,7 +41,7 @@ fun SourceFilterDialog(
     val updateFilters = { onUpdate(filters) }
 
     AdaptiveSheet(
-        onDismissRequest = onDismissRequest,
+        onDismissRequest = onDismissRequest
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceFilterDialog.kt:44]: Why?

File: presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt [hunk 2]
```diff
@@ -167,7 +167,9 @@ fun AdaptiveSheet(
                     .offset {
                         IntOffset(
                             0,
-                            anchoredDraggableState.offset.takeIf { it.isFinite() }?.roundToInt() ?: 0,
+                            anchoredDraggableState.offset
+                                .takeIf { it.isFinite() }
+                                ?.roundToInt() ?: 0,
```
Comment (AntsyLich) [inline presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt:172]:
```suggestion
                                ?.roundToInt() 
                                ?: 0,
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

**Comment by arkon** [comment]
Thanks!
