### PR TITLE
Fix download ahead missing out 1 chapter

### LINKED ISSUE #7917: Download ahead missing out 1 chapter.
### Steps to reproduce

Happens when all downloaded chapters are read

Set download ahead to X amount.
1. Get a manga with X+2 chapters. 
2. Download chapter 1 and 2
3. Read chapter 1 and 2

### Expected behavior

Upto Chapter X+2 should be in download queue

### Actual behavior

Only upto Chapter X+1 is in queue while Chapter X+2 is not added

### Crash logs

_No response_

### Tachiyomi version

r4845 

### Android version

N/A

### Device

N/A

### Other details

Should add a check for if it's the last downloaded chapter then instead of just next one it should add next 2 chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by nzoba**
Closes #7917

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/util/system/BooleanExtensions.kt [hunk 1]
```diff
@@ -0,0 +1,3 @@
+package eu.kanade.tachiyomi.util.system
+
+fun Boolean.toInt() = if (this) 1 else 0
```
Comment (ghostbear) [inline app/src/main/java/eu/kanade/tachiyomi/util/system/BooleanExtensions.kt:3]: You could move this function into this file as well

https://github.com/tachiyomiorg/tachiyomi/blob/809da49301cceacd433f38354fb04fc616efcc5f/app/src/main/java/eu/kanade/data/DatabaseUtils.kt

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt [hunk 2]
```diff
@@ -452,12 +453,12 @@ class ReaderPresenter(
         val isNextChapterDownloaded =
             downloadManager.isChapterDownloaded(nextChapter.name, nextChapter.scanlator, manga.title, manga.source)
         if (isNextChapterDownloaded) {
-            downloadAutoNextChapters(chaptersNumberToDownload, nextChapter.id)
+            downloadAutoNextChapters(chaptersNumberToDownload, nextChapter.id, nextChapter.read)
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt:456]: Won't this be invoked every time? Since next chapter always won't be read

Comment (nzoba) [reply app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt:456]: I think I misunderstood your issue. I thought you were talking about the rare case where the next chapter is already read and downloaded (and you don't have the setting `skip chapters marked read` enabled) then it would be included in the next unread chapters count even thought it's already read

I think your issue happens if you read too fast and the next chapter is not yet downloaded (still in the queue), so the last read chapter won't add a chapter to the queue (since one of the condition is that the next chapter should already be downloaded). Let me know if I understood correctly this time :sweat_smile: 
I can add a check whether the next one is already downloaded or in the queue to fix that

Comment (AntsyLich) [reply app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt:456]: yup that's the issue

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt [hunk 3]
```diff
@@ -449,15 +450,19 @@ class ReaderPresenter(
...
         if (chaptersNumberToDownload == 0 || !manga.favorite) return
-        val isNextChapterDownloaded =
-            downloadManager.isChapterDownloaded(nextChapter.name, nextChapter.scanlator, manga.title, manga.source)
-        if (isNextChapterDownloaded) {
-            downloadAutoNextChapters(chaptersNumberToDownload, nextChapter.id)
+        val isNextChapterDownloadedOrQueued = downloadManager.isChapterDownloaded(
+            nextChapter.name,
+            nextChapter.scanlator,
+            manga.title,
+            manga.source,
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt:457]: do a `skipCache = true` check

Comment (nzoba) [reply app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt:457]: Is it really necessary in this case ? While you are reading you probably won't touch your downloads via the file system so the cache should be enough no ? And it's faster to check the cache
