### PR TITLE
Fix "Download split" not working while using SD card

### LINKED ISSUE #7457: "Couldn't split downloaded image" (not due to RAM)
### Steps to reproduce

Try downloading a webtoon, in my latest case "The Tutorial is Too Hard" from MangaSee.

### Expected behavior

It shouldn't show that error, got it on some webtoons so far.

### Actual behavior

My reader's still laggy and I have an error message 24/7.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9041878/tachiyomi_crash_logs.txt)
[logcat_07-03-2022_01-01-37.txt](https://github.com/tachiyomiorg/tachiyomi/files/9041879/logcat_07-03-2022_01-01-37.txt)

### Tachiyomi version

r4553

### Android version

Android 10

### Device

Moto G7 Power

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AntsyLich**
It doesn't automagically create a new file when you open output stream of a non-existing file on SD card

Closes #7457

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt [hunk 1]
```diff
@@ -221,11 +219,15 @@ object ImageUtil {
 
         return try {
             splitDataList.forEach { splitData ->
-                val splitPath = splitImagePath(imageFilePath, splitData.index)
+                val splitImageName = splitImageName(filenamePrefix, splitData.index)
+                // Remove pre-existing split if exists (this split shouldn't exits under normal circumstances)
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt:223]:
```suggestion
                // Remove pre-existing split if exists (this split shouldn't exist under normal circumstances)
```
