### PR TITLE
Fix search inputs accepting formatted text

### LINKED ISSUE #6495: Global and extension search input accepts formatted text
### Steps to reproduce

1. Open the Browse section.
2. Paste a formatted text into the global or extension search input.

### Expected behavior

It should not accept a formatted text and the simple value should appear instead.

### Actual behavior

The formatted text pastes just fine.

### Crash logs

_No response_

### Tachiyomi version

r4103

### Android version

Android 12

### Device

Samsung Galaxy S20+

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by afreakyelf**
Fixes #6495

### CODE REVIEW

**Review by arkon — COMMENTED** [review]
This seems to have a negative impact on the actual performance (e.g., it's noticeably laggy when inputting text or holding backspace).

**Comment by afreakyelf** [comment]
Do you have anything in mind that we can implement or make changes to my PR?

**Comment by arkon** [comment]
You may be able to check if there's actually formatting (check for presence of some spans?) or potentially check if the pre and post-removal strings are the same (which I assume would be different?) prior to setting the selection to reset the cursor (which is what I think would be causing the "lag").

**Comment by afreakyelf** [comment]
Sure let me give it a try.

**Comment by afreakyelf** [comment]
Hi @arkon, I have pushed the change and it seems to be working now. Can have a look please.

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 1]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
         searchItem.fixExpand(onExpand = { invalidateMenuOnExpand() })
         searchView.maxWidth = Int.MAX_VALUE
 
+        // TO remove formatting from clipboard text #6495
+        val searchAutoComplete: SearchView.SearchAutoComplete = searchView.findViewById(
+            R.id.search_src_text
+        )
+        searchAutoComplete.addTextChangedListener(object : TextWatcher {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:66]: We could probably move this to be within `TachiyomiSearchView`.

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 2]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
+                // TODO("Not yet implemented")
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:68]: Remove TODOs

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 3]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+            }
+
+            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
+                // TODO("Not yet implemented")
+            }
+
+            override fun afterTextChanged(s: Editable?) {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:75]: Use more meaningful variable names

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 4]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+                val spannable: Array<StyleSpan> = s!!.getSpans(
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:76]: Try to avoid `!!` if this really is nullable

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 5]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+                    0, 5,
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:77]: Why 5?

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 6]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+                    StyleSpan::class.java
+                )
+                if (spannable.isNotEmpty()) {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:80]: This check isn't really necessary

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 7]
```diff
@@ -52,6 +59,32 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+                    for (i in spannable.indices) {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:81]: Use something like `.forEach {}` instead of a for loop

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 8]
```diff
@@ -135,6 +168,12 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
         )
     }
 
+    // To format the text
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:171]: This is misleading, it removes formatting. Can just remove it and rename the function to something more meaningful (e.g. `removeFormatting`)

**Review by arkon — CHANGES_REQUESTED** [review]

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt (hunk 1 above)
Comment (afreakyelf) [reply app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:63]: I tried but addTextChangedListener is not populating. Rest changes I have made. Please check again

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 9]
```diff
@@ -52,6 +56,26 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
         searchItem.fixExpand(onExpand = { invalidateMenuOnExpand() })
         searchView.maxWidth = Int.MAX_VALUE
 
+        // TO remove formatting from clipboard text #6495
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:59]:
```suggestion
        // Remove formatting from pasted text
```

File: app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt [hunk 10]
```diff
@@ -52,6 +56,26 @@ abstract class SearchableNucleusController<VB : ViewBinding, P : BasePresenter<*
...
+            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {}
+
+            override fun afterTextChanged(editable: Editable) {
+                val spannable: Array<StyleSpan> = editable.getSpans(
+                    0, editable.length,
+                    StyleSpan::class.java
+                )
+                spannable.forEachIndexed { index, _ ->
+                    editable.removeSpan(spannable[index])
+                }
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt:75]:
```suggestion
                editable.getSpans(0, editable.length, StyleSpan::class.java)
                    .forEach { editable.removeSpan(it) }
```

Comment (afreakyelf) [reply app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt]: Done, Please check.

Comment (afreakyelf) [reply app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt]: Can you please approve it if nothing is left to modify.

**Review by arkon — APPROVED** [review]

**Comment by alessandrojean** [comment]
Just letting you know that your modifications did not fix the issue, it still happens in r4118.

SmartSelect_20220129-194812_Tachiyomi

**Comment by arkon** [comment]
Odd, I thought I tested it too but maybe the text I copied wasn't formatted.
