### PR TITLE
LibrarySettingsSheet: Fix race condition when applying sort mode

### LINKED ISSUE #7735: Library manga sorting always resets to alphabetical
### Steps to reproduce

1. open library sorting
2. try to change the sort to anything

### Expected behavior

sorting should be the one i select

### Actual behavior

sorting resets to alphabetical no matter what

### Crash logs

_No response_

### Tachiyomi version

4739

### Android version

Android 12

### Device

Galaxy A72

### Other details

per category settings for sort and display was on in library setting

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ivaniskandar**
Also fix sort direction can't be changed for default category

Fixes #7735

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt [hunk 1]
```diff
@@ -273,9 +278,14 @@ class LibrarySettingsSheet(
...
                 }
+                val direction = if (item.state == Item.MultiSort.SORT_ASC) {
+                    SortDirectionSetting.ASCENDING
+                } else {
+                    SortDirectionSetting.DESCENDING
+                }
 
                 sheetScope.launchIO {
-                    setSortModeForCategory.await(currentCategory!!, flag)
+                    setSortModeForCategory.await(currentCategory!!, mode, direction)
```
Comment (ghostbear) [inline app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt:288]: Remove the overload functions as they are now longer

File: app/src/main/java/eu/kanade/tachiyomi/ui/library/setting/SortDirectionSetting.kt [hunk 2]
```diff
@@ -15,7 +15,7 @@ enum class SortDirectionSetting(val flag: Long) {
         }
 
         fun get(preferences: PreferencesHelper, category: Category?): SortDirectionSetting {
```
Comment (ghostbear) [inline app/src/main/java/eu/kanade/tachiyomi/ui/library/setting/SortDirectionSetting.kt:17]: We can stop using this as the `category.sortDirection` is the truth

**Review by ghostbear — COMMENTED** [review]
I don't feel like the change to use `getCategories.subscribe()` is necessary as `_currentCategory` is only used to set up the `LibrarySettingsSheet` state once and then any update to the flags is reflected through the user actions

**Review by ghostbear — APPROVED** [review]
