### PR TITLE
Detect identical mangas when long pressing to add to library

### LINKED ISSUE #6640: "Detect identical manga" doesn't work for source view "long press to add to library"
### Steps to reproduce

Go to any source
Long press any manga that has a duplicate name in library

### Expected behavior

"Identical manga" dialog appears

### Actual behavior

Adds to library immediately

### Crash logs

_No response_

### Tachiyomi version

r4159

### Android version

A11

### Device

Redmi Note 9 Pro (ArrowOS)

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by CVIUS**
Closes #6640

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt [hunk 1]
```diff
@@ -605,47 +609,77 @@ open class BrowseSourceController(bundle: Bundle) :
...
+                    }
+                }.toTypedArray()
+
+                ChangeMangaCategoriesDialog(this, listOf(manga), categories, preselected)
+                    .showDialog(router)
             }
         }
     }
 
+    private fun showAddDuplicateDialog(newManga: Manga, libraryManga: Manga, position: Int) {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt:666]: I feel like this needs to be extracted into its own dialog class to avoid some duplication. Would you be able to do that as part of this PR?

Comment (tanuukii) [reply app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt:666]: I'm afraid not

Comment (CVIUS) [reply app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt:666]: I don't think I can😅

Comment (arkon) [reply app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt:666]: I've extracted it in e421eb61bc7b4bcaf10b7e165358de83d2bfe368, so you can try using that.

File: app/src/main/java/eu/kanade/tachiyomi/ui/manga/AddDuplicateMangaDialog.kt [hunk 2]
```diff
@@ -18,12 +18,14 @@ class AddDuplicateMangaDialog<T>(bundle: Bundle? = null) : DialogController(bund
 
     private lateinit var libraryManga: Manga
     private lateinit var newManga: Manga
+    private var position: Int? = null
 
-    constructor(target: T, libraryManga: Manga, newManga: Manga) : this() {
+    constructor(target: T, libraryManga: Manga, newManga: Manga, position: Int? = null) : this() {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/manga/AddDuplicateMangaDialog.kt:23]: I updated this class so that you don't need to pass in a `position` anymore and instead keep that in the controller.

Comment (CVIUS) [reply app/src/main/java/eu/kanade/tachiyomi/ui/manga/AddDuplicateMangaDialog.kt]: Idk if I did your suggestion correctly, but yea. LMK

File: app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt [hunk 3]
```diff
@@ -605,43 +608,58 @@ open class BrowseSourceController(bundle: Bundle) :
...
+        }
+    }
 
-                    presenter.changeMangaFavorite(manga)
+    override fun addToLibrary(newManga: Manga) {
+        val activity = activity ?: return
+        val categories = presenter.getCategories()
+        val defaultCategoryId = preferences.defaultCategory()
+        val defaultCategory = categories.find { it.id == defaultCategoryId }
+        val position = adapter?.currentItems?.indexOfFirst { it -> (it as SourceItem).manga.id == newManga.id }
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt:625]: I think you could've just passed the `position` to the `addToLibrary` call on line 612.
