### PR TITLE
Use "isOnline" utils in DownloadService

### LINKED ISSUE #5831: New Downloader Bugs
## First Case
Disable Internet while downloading a chapter and then reconnect.

## Second Case
Kinda Hard to Reproduce you have to make it such that your data runs out while downloading.

## First Case
When Disconnected:
1. Shows "No network available" error notification.
2. Download stops (Downloader doesn't get paused).

When Reconnected:
1. Download continues

## Second Case
Download Stops (Downloader doesn't get paused) 

## First Case
When Disconnected:
1. Download stops (Downloader doesn't get paused).

When Reconnected:
1. Shows "No network available" error notification.
2. Download doesn't continue (Have to pause and resume again to start the download)

## Second Case
 Download continues and fails one by one making the downloader stop (It gets paused).

### Crash logs

N/A

### Tachiyomi version

0.12.1-3756

### Android version

Android 6

### Device

LAVA iris820

### Other details

Probably causes by the recent changes in PR #5785 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FourTOne5**
Fixes #5831

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt [hunk 1]
```diff
@@ -155,30 +153,25 @@ class DownloadService : Service() {
...
-            return stopDownloads(R.string.download_notifier_no_network)
-        }
-
-        if (preferences.downloadOnlyOverWifi() && !wifiManager.isWifiEnabled) {
-            stopDownloads(R.string.download_notifier_text_only_wifi)
-        } else {
-            val started = downloadManager.startDownloads()
-            if (!started) stopSelf()
+        when (isOnline()) {
+            true -> {
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt:157]: Just do an `if`/`else`

Comment (FourTOne5) [reply app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt]: Ok
