### PR TITLE
Remove extra padding when using list with Per Category setting 

### LINKED ISSUE #5636: Margin in List view when using "Per-category sort/display settings"
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3631

### Android version

Android 10

### Device

Redmi Note 9 Pro

### Steps to reproduce

Have "Per category sort/display settings" on
Use List view for Library

### Expected behavior

No margin

### Actual behavior

Has margin

### Crash logs

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by ghostbear**
fixes #5636

| Before | After |
| ------- | ------- |
| Screenshot_1633070104 | Screenshot_1633069961 |

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt [hunk 1]
```diff
@@ -131,10 +132,22 @@ class LibraryCategoryView @JvmOverloads constructor(context: Context, attrs: Att
...
+                    0,
+                    0,
+                    0,
+                    context.resources.getDimension(R.dimen.action_toolbar_list_padding).roundToInt()
+                )
             } else {
-                controller.mangaPerRow
+                recycler.spanCount = controller.mangaPerRow
+                recycler.setPadding(
+                    5.dpToPx,
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt:146]: Where does 5 come from?

Comment (ghostbear) [reply app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt:146]: It comes from `library_grid_recycler.xml`

Comment (arkon) [reply app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt:146]: I wonder if we can refactor out the creation from `onCreate` so that it's actually inflating the different layouts instead?

Comment (ghostbear) [reply app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt:146]: I have tried moving the creation out of `onCreate` but I don't seem to get it to work
