### PR TITLE
Case insensitive sort in extension list.

### LINKED ISSUE #6373: case insensitive sort in extension list
### Steps to reproduce

Open extension list (edit: *not* source list)

### Expected behavior

oots is in the middle, aurora is near the top

### Actual behavior

oots, aurora, buttsmithy,etc are all at the bottom of the list, below Zin

### Crash logs

_No response_

### Tachiyomi version

0.12.3

### Android version

11

### Device

tab s6

### Other details

App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T860XXU4CUI4
Device brand: samsung
Device manufacturer: samsung
Device name: gts6lwifi
Device model: SM-T860
Device product name: gts6lwifixx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FourTOne5**
Closes #6373

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionPresenter.kt [hunk 1]
```diff
@@ -63,9 +63,9 @@ open class ExtensionPresenter(
 
         val items = mutableListOf<ExtensionItem>()
 
-        val updatesSorted = installed.filter { it.hasUpdate && (showNsfwSources || !it.isNsfw) }.sortedBy { it.name }
-        val installedSorted = installed.filter { !it.hasUpdate && (showNsfwSources || !it.isNsfw) }.sortedWith(compareBy({ !it.isObsolete }, { it.name }))
-        val untrustedSorted = untrusted.sortedBy { it.name }
+        val updatesSorted = installed.filter { it.hasUpdate && (showNsfwSources || !it.isNsfw) }.sortedBy { it.name.lowercase() }
```
Comment (arkon) [inline app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionPresenter.kt:66]: Use `.sortedWith(compareBy(String.CASE_INSENSITIVE_ORDER, { it.name }))` to avoid creating new strings.
