### PR TITLE
ExtensionScreen: Adjust item visual

### LINKED ISSUE #8052: ExtensionScreen: ExtensionItemContent's bottom row overflow
### Steps to reproduce

Go to extension screen. Enable a language with a long name. Download an extension of it.

### Expected behavior

Overflow handled.

### Crash logs

_No response_

### Tachiyomi version

r4929

### Android version

Android 12

### Device

Not related

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ivaniskandar**
* Move install status view and add progress indicator
* Add secondary item modifier to info texts
* Wrap info texts with FlowRow in case of unavailable space (Closes #8052)
* Remove language text in non-installed items

Extra content:
* Change the list key to be more consistent
* General cleanups

### CODE REVIEW

File: app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt [hunk 1]
```diff
@@ -301,46 +337,38 @@ private fun ExtensionItemActions(
...
                         }
-                    }
-                },
-                style = LocalTextStyle.current.copy(
-                    color = if (isIdle) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surfaceTint,
-                ),
-            )
-        }
-        if (isIdle.not()) {
+                        else -> error("Must now show install process text")
```
Comment (arkon) [inline app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt:363]: Did you mean "not"?

Comment (ivaniskandar) [reply app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt:363]: oopsie
